[package]
name = "po-crdt-proc"
version = "0.1.0"
edition = "2021"
authors = ["Léo Olivier <leo.olivier@cea.fr>"]
description = ""
license = "proprietary"

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = "2.0.101"

[lib]
proc-macro = true

[features]

[profile.release]
debug = 1
